### ISSUE TITLE
In Event Creation Not able to select Location from the drop Down

### ISSUE THREAD

**Issue by sshrivastava8** [she-smashes/thehub#146]
In Event Creation Not able to select Location from the drop Down
Scenario: 1. Click on Create Event, enter all detail, then try to select location from dropdown
Issue: Dropdown is getting open but not able to select location.
![locationselectionnotworking](https://user-images.githubusercontent.com/35568628/35103494-00e2231e-fc8c-11e7-888f-23a7fac8cdd3.png)

**Comment by ragasudhaa** [comment]
The location is a multi select dropdown, so once location is selected, user has to click outside the field to select the values.

**Comment by sshrivastava87** [comment]
Misunderstood of requirement, hence closing the issue. But the current UI is not user friendly.
